### PR TITLE
Compota great refactoring 

### PR DESCRIPTION
**Pull request by evdokim**
* wrapping all java exceptions to Try
* tail rec instead loops and vars
* centralized logging
* splitting code into abstract compota and aws compota
* local compota

### CODE REVIEW

**Comment by eparejatobes** [comment]
This branch has been open for 7 months already. This seriously hinders any logical branch management in this repo. Let's merge this before any further work.

**Comment by evdokim** [comment]
I will merge it once It will work. Some thing for AWS compota version are still missing (aws console, logging management).

**Comment by eparejatobes** [comment]
Any further development can happen on feature specific branches, as it should. I am sorry for any inconvenience this may cause you, but I'm merging this.

**Comment by evdokim** [comment]
Right now master branch has a old but working version Compota. I don't carry a lot if you do this merge, but I don't see a lot of sense since I will merge the new working version pretty soon.

**Comment by eparejatobes** [comment]
I'm sorry but I don't understand you. Anyway, if master has something that should be a version, create a tag for that (at the very least). This sort of issue is caused by not making proper releases.

**Comment by eparejatobes** [comment]
merging then

**Pull request merged**
